// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication_ASP_React_Test.Models;

namespace WebApplication_ASP_React_Test.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201129145406_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApplication_ASP_React_Test.Models.Order", b =>
                {
                    b.Property<int>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("addressRecipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("addressSender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cityRecipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("citySender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateTaken")
                        .HasColumnType("datetime2");

                    b.Property<double>("weight")
                        .HasColumnType("float");

                    b.HasKey("orderId");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
